title: My Portfolio!
author: Keragan Cavolo
email: keragan.cavolo@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my portfolio! Here, you will find examples of my personal and professional projects! I am a huge fan of R, so that is why my projects tend to be done with it. But I am also proficient in SQL, Microsoft Excel, and Google Sheets. Check out my [resume]() for a full overview of my background! 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
linkedin_username: keragancavolo

show_excerpts: true # set to false to remove excerpts on the homepage
